spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

feign:
  client:
    config:
      payment-service:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: FULL

server:
  port: 8080

logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: BASIC

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080
  url: localhost:9080/api

user-service:
  api-version: /api/v1
  available-tariffs:
    super-user:
      shows: 100
      days: 1
      price: 100
      currency: 'USD'
      priority: 1
    priority-user:
      shows: 50
      days: 1
      price: 75
      currency: 'USD'
      priority: 2
  recommendation-request:
    min-month: 6
    