spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        subscription-channel: subscription_channel
        mentorship-channel: mentorship_channel
        follower-channel: follower_event
        recommendation-channel: recommendation_channel
        goal-completed: goal_completed_channel
        user-ban-channel: user_ban_channel
        mentorship-request: mentorship_request_channel
        event-start-event-channel: event_start_event_channel

  retry:
    maxAttempts: 3
    initialDelay: 1000
    multiplier: 2
    maxDelay: 10000

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

minio:
  url: http://localhost:9000
  accessKey: LbtJkdBst2Fzh9PQWMbn
  secretKey: ZQsUFl0ToSUn8U6xH6dAoBnpWruKS0kvkiAvsVXN
  bucketName: avatars
  publicPolicy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": "*",
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::avatars/*"
        }
      ]
    }

project-service:
  host: localhost
  port: 8082

payment-service:
  host: http://localhost
  port: 9080


cron:
  expressions:
    clear-published-events: "0 0 0 * * *"
    clear-events: "0 0 0 * * *"
    clean-outbox: "0 0 0 * * *"
    trigger-outbox-processing: "0 */1 * * * *"
    load-upcoming-events: "0 0 0 */2 * *"
    publish-event-start-event-fixed-rate: "0/30 * * * * *"

scheduler:
  core-pool-size: 4
  event-start-notification:
    upload-events-days-batch: 2
    duration-to-publish-event-start-event-milliseconds: 86400000, 18000000, 3600000, 600000


batch:
  size:
    eventBatch: 50

myapp:
  schedule:
    cron: "0 0 0 * * MON"

del:
  batch-size: 100