spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        mentorship-channel:
          name: mentorship_channel
        follower-event-channel:
          name: follower_event
        ban_user_topic:
          name: user_ban

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 505043354003-fr1slmod1spf1a49gr9ub46pto40u5b1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/calendar
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"

server:
  port: 8080

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://127.0.0.1:9000/
    accessKey: user
    secretKey: password
    region: us-east-1
    bucketName: corpbucket
    isMocked: false

  payment-service:
    host: http://localhost
    port: 9080

  user-service:
    host: http://localhost
    port: 8080

  project-service:
    host: localhost
    port: 8082

removeEventTime:
  cron: 0 0 * * * *

