spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        mentorship-channel: mentorship_channel
        follower-channel: follower_event
        recommendation-channel: recommendation_channel
        goal-completed: goal_completed_channel
        user-ban-channel: user_ban_channel
        mentorship_request: "mentorship_request_channel"


  retry:
    maxAttempts: 3
    initialDelay: 1000
    multiplier: 2
    maxDelay: 10000


server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

minio:
  url: http://localhost:9000
  accessKey: LbtJkdBst2Fzh9PQWMbn
  secretKey: ZQsUFl0ToSUn8U6xH6dAoBnpWruKS0kvkiAvsVXN
  bucketName: avatars
  publicPolicy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": "*",
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::avatars/*"
        }
      ]
    }

project-service:
  host: localhost
  port: 8082

payment-service:
  host: http://localhost
  port: 9080

cron:
  expressions:
    clearEvents: "0 0 0 * * *"

batch:
  size:
    eventBatch: 50

myapp:
  schedule:
    cron: "0 0 0 * * MON"

del:
  batch-size: 100