spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      port: 6379
      host: localhost

  servlet:
    multipart:
      max-file-size: 5MB

swagger:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080

logging:
  level:
    root: info

s3:
  endpoint: http://localhost:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

goal:
  max-active-goals-per-user: 3

image:
  avatar:
    folder-name: users_avatars
    sizes:
      large: 1080
      small: 170