spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        mentorship-channel:
          name: mentorship_channel
        follower-event-channel:
          name: follower_event

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

storage:
  type: minio
  bucketName: corpbucket

minio:
  url: http://localhost:9000
  accessKey: user
  secretKey: password
  region: eu

aws:
  accessKey:
  secretKey:
  region:

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080


cron:
  expressions:
    clearEvents: "0 0 0 * * *"

batch:
  size:
    eventBatch: 50
