spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  profiles:
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        user-ban-channel:
          name: user-ban-event
        search-appearance-channel:
          name: search-appearance-event
        project-follower-channel:
          name: project-follower-channel
        bought-premium:
          name: bought_premium_channel

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

api-docs:
  enabled: true
swagger-ui:
  enabled: true
  path: /swagger-ui.html

event-cleanup:
  chunkSize: 100
  threadNumber: 10
  cron:
    expression: "0 0 10 * * SUN"
