name: CI Pipeline

on:
  pull_request:
    branches:
      - chimera-master-stream8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run CheckStyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --continue

      - name: Run Tests
        run: ./gradlew test --no-daemon