name: CI

on:
  push:
    branches:
      - basilisk8/BJS2-52756-ci-pipeline
  pull_request:
    branches:
      - basilisk8/BJS2-52756-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Checkstyle on changed files
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Build and run tests
        run: ./gradlew test

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
