name: Build and Test Coverage Validation

on:
  pull_request:
    branches:
      - 'kraken-master-stream8'
  push:
    branches:
      - 'kraken-master-stream8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Gradle Package
        run: ./gradlew clean build

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Verify Test Coverage
        run: ./gradlew jacocoTestCoverageVerification